
test_that("base plot works - vdiffr", {
  # Use vdiffr to generate a snapshot of the plot
  # If we expect_doppelganger again, the snapshot should be the same
  expect_doppelganger("plot", gen_base_plot)
  expect_doppelganger("plot", gen_base_plot)
})


test_that("base plot works - visualTest", {
  # The plot generated by the same code should be the same
  tmp <- tempfile(fileext = ".png")
  png(tmp)
  gen_base_plot()
  dev.off()
  expect_true(isImageSimilar(tmp, "base_plot.png"))
})


test_that("ggplot works - vdiffr", {
  # Test using the snapshot generated by vdiffr
  expect_doppelganger("ggplot point plot", gen_ggplot_point())
  expect_doppelganger("ggplot point plot", gen_ggplot_point())
})


test_that("ggplot works - visualTest", {
  # Test using visualTest for the generated image
  tmp <- tempfile(fileext = ".png")
  png(tmp)
  print(gen_ggplot_point())
  dev.off()
  expect_true(isImageSimilar(tmp, "ggplot_point.png"))
})


test_that("base plot expects failure - vdiffr", {
  # No snapshot for failing
  # So should fail
  expect_doppelganger("failing", gen_base_plot)
})


test_that("base plot expects failure - visualTest", {
  # visualTest can compare the generated image with the expected image
  # with a different plot
  tmp <- tempfile(fileext = ".png")
  png(tmp)
  plot(1:20)  # original plot is 1:10
  dev.off()
  expect_false(isImageSimilar(tmp, "base_plot.png"))
})


test_that("ggplot expects failure - vdiffr", {
  # Code has been changed so that it should fail
  genplot = function() {
    gen_ggplot_point() + theme_bw()
  }

  expect_doppelganger("ggplot original plot", gen_ggplot_point())
  expect_failure({
    expect_doppelganger("ggplot original plot", genplot())
  })
})


test_that("ggplot expects failure - visualTest", {
  # visualTest can compare the generated image with the expected image
  # with a different theme
  tmp <- tempfile(fileext = ".png")
  # A different theme should fail
  p <- gen_ggplot_point() + theme_bw()
  png(tmp)
  print(p)
  dev.off()
  expect_false(isImageSimilar(tmp, "ggplot_point.png"))
})
